name: CI
on: [push, pull_request]

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Setup Go environment
          uses: actions/setup-go@v2.0.3
          with:
            go-version: 1.14
        - name: Repo checkout
          uses: actions/checkout@v2.2.0
        - name: Test
          run: go test -tags integration_tests ./...